#!/bin/bash

echo "=========================================="
echo "Supabase DATABASE_URL Bulma Rehberi"
echo "=========================================="
echo ""
echo "1. https://supabase.com adresine gidin"
echo "2. Giriş yapın ve projenizi seçin"
echo "3. Sol menüden 'Settings' (⚙️) ikonuna tıklayın"
echo "4. 'Database' sekmesine gidin"
echo "5. 'Connection string' bölümünü bulun"
echo "6. 'URI' formatını seçin"
echo "7. Connection string'i kopyalayın"
echo "8. Şifrenizi [YOUR-PASSWORD] yerine yazın"
echo "9. .env dosyasındaki DATABASE_URL satırını güncelleyin"
echo ""
echo "Örnek format:"
echo "postgresql://postgres:[ŞİFRE]@db.[PROJECT-REF].supabase.co:5432/postgres"
echo ""
echo "Detaylı rehber için: SUPABASE_DATABASE_URL_GUIDE.md dosyasına bakın"
